- action:
  - alias: ''
    data: {}
    service: cover.close_cover
  alias: Secure Home, Stay
  condition: []
  id: '1519348624408'
  trigger:
  - entity_id: alarm_control_panel.simplisafe
    from: disarmed
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.simplisafe
    from: armed_away
    platform: state
    to: armed_home
- action:
  - data:
      entity_id: cover.garage_door_opener
    service: switch.turn_off
  - data:
      entity_id: cover.garage_door_opener
    service: cover.close_cover
  alias: Secure Home, Away
  condition: []
  id: '1519775124178'
  trigger:
  - entity_id: alarm_control_panel.home_security
    from: disarmed
    platform: state
    to: armed_away
  - entity_id: alarm_control_panel.home_security
    from: armed_home
    platform: state
    to: armed_away
- action:
  - service: switch.turn_on
  alias: Turn On Upstairs AC
  hide_entity: true
  condition: []
  id: '1520379769803'
  trigger:
  - above: '80'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
- action:
  - data:
      entity_id: switch.lamp
    service: switch.turn_off
  hide_entity: true
  alias: Turn Off Upstairs AC
  condition: []
  id: '1520379886802'
  trigger:
  - below: '78'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  - at: '23:00:00'
    platform: time
- action:
  - data:
      entity_id: switch.fireplace
    service: switch.turn_on
  alias: Night Light On
  condition: []
  id: '1520389956382'
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
- action:
  - data:
      entity_id: switch.fireplace
    service: switch.turn_off
  alias: Night Light Off
  condition: []
  id: '1520390163853'
  trigger:
  - at: '22:35:00'
    platform: time
