- id: '1519348624408'
  alias: Security - Home Mode
  trigger:
  - entity_id: alarm_control_panel.simplisafe
    from: disarmed
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.simplisafe
    from: armed_away
    platform: state
    to: armed_home
  condition: []
  action:
  - alias: ''
    data: {}
    service: cover.close_cover
- id: garage_state_change
  alias: Notification - Garage State Change
  trigger:
  - entity_id: cover.garage_door_opener
    from: open
    platform: state
    to: closed
  - entity_id: cover.garage_door_opener
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: Garage door opened/closed
    service: script.internal_notification
  initial_state: 'on'
- id: '1519775124178'
  alias: Security - Away Mode
  trigger:
  - entity_id: alarm_control_panel.home_security
    from: disarmed
    platform: state
    to: armed_away
  - entity_id: alarm_control_panel.home_security
    from: armed_home
    platform: state
    to: armed_away
  condition: []
  action:
  - delay: '[object Object]'
  - data:
      entity_id: cover.garage_door
    service: cover.close_cover
  - data:
      entity_id: switch.master_tv
    service: switch.turn_off
  - data:
      entity_id: switch.living_tv_
    service: switch.turn_off
  - data:
      message: Away Mode activated
    service: script.global_notification
- id: '1520379769803'
  alias: Climate - Turn On Window AC
  trigger:
  - above: '82'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_on
- id: 1520379886802a
  alias: Climate - Turn Off Window AC
  trigger:
  - below: '81'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  - at: '23:45:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_off
- id: '1521315030622'
  alias: Security - Garage Home while Secure Home
  trigger:
  - entity_id: cover.garage_door
    from: closed
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_security
    state: armed_home
  action:
  - data:
      entity_id: switch.living_lamp
    service: switch.turn_on
  - data:
      message: Garage door has opened while secured!
    service: script.global_notification
- id: '1520389956382'
  alias: Night Light On
  hide_entity: true
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
  action:
  - data:
      entity_id: switch.living_lamp
    service: switch.turn_on
- id: morning_news
  alias: Morning News
  trigger:
  - platform: time
    at: 06:25:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: switch.master_tv
    service: switch.turn_on
- id: morning_news_end
  alias: Morning News Signoff
  trigger:
  - platform: time
    at: 07:55:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: switch.master_tv
    service: switch.turn_off
- id: '1520390163853'
  alias: Night Light Off
  trigger:
  - at: '22:35:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.living_lamp
    service: switch.turn_off
- id: notification_restart
  alias: Notification - Home Assistant Restart
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      message: Home Assistant has restarted.
    service: script.internal_notification
- id: update_notifications
  alias: Notification - Update Home Assistant
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data_template:
      message: Home Assistant  {{ states.updater.updater.state }}  is now available.
      title: New Home Assistant Release
    service: notify.global_notification
- alias: Climate - Turn On Window AC, Vacation
  trigger:
  - above: '85'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_on
- id: '1520379886802'
  alias: Climate - Turn Off Window AC, Vacation
  trigger:
  - below: '84'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  - at: '23:45:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_off
- id: switch_on_modem
  alias: Switch On Modem
  trigger:
  - event: start
    platform: homeassistant
  - platform: time
    minutes: 5
    seconds: 0
  - platform: time
    minutes: 35
    seconds: 0
  action:
  - delay: 00:05:00
  - data:
      entity_id: switch.cable
    service: switch.turn_on
- id: disable_vacation_mode_on_return
  alias: Disable Vacation Mode on Return
  trigger:
  - entity_id: alarm_control_panel.home_security
    platform: state
    from: away
    to: disarmed
  - entity_id: alarm_control_panel.home_security
    platform: state
    from: away
    to: home
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.vacation_mode
- id: trash_day_notification
  alias: Notification - Trash Day
  trigger:
  - at: '17:30:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - thu
  action:
  - data:
      message: Today is trash day
      notification_id: '92349823748923749'
      title: Trash Day Reminder
    service: persistent_notification.create
- id: dismiss_trash_notification
  alias: Notification - Trash Day Dismiss
  trigger:
  - at: '14:40:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - tue
    - fri
  action:
  - data:
      notification_id: '92349823748923749'
    service: persistent_notification.dismiss
