- action:
  - alias: ''
    data: {}
    service: cover.close_cover
  alias: Secure Home, Stay
  condition: []
  id: '1519348624408'
  trigger:
  - entity_id: alarm_control_panel.simplisafe
    from: disarmed
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.simplisafe
    from: armed_away
    platform: state
    to: armed_home
- action:
  - data:
      entity_id: cover.garage_door_opener
    service: switch.turn_off
  - data:
      entity_id: cover.garage_door_opener
    service: cover.close_cover
  alias: Secure Home, Away
  condition: []
  id: '1519775124178'
  trigger:
  - entity_id: alarm_control_panel.home_security
    from: disarmed
    platform: state
    to: armed_away
  - entity_id: alarm_control_panel.home_security
    from: armed_home
    platform: state
    to: armed_away
