################################################################################
# kodi
################################################################################
- platform: kodi
  host: !secret office_ip
  name: Kodi Office
- platform: kodi
  host: !secret media_ip
  name: Kodi Media

################################################################################
# plex
################################################################################

- platform: plex
  name: Plex
  ip_address: !secret media_ip
  entity_namespace: plex
  show_all_controls: True

################################################################################
# Roku
################################################################################

- platform: roku
  host: !secret roku_bedroom1
  name: Roku Bedroom 1
- platform: roku
  name: Roku Office
  host: !secret roku_office
- platform: roku
  name: Roku Living
  host: !secret roku_living

