# Weather Underground
- platform: wunderground
  api_key: !secret weather_api_key
  monitored_conditions:
    - alerts
    - temp_f
    - weather

- platform: yweather
  monitored_conditions:
    - weather
    - temperature
    - humidity
    - visibility

- platform: plex
  host: media_ip
  ssl: True
