# Weather Underground
- platform: wunderground
  api_key: !secret weather_api_key
  monitored_conditions:
    - alerts
    - temp_f
    - weather

- platform: yweather
  monitored_conditions:
    - weather
    - temperature
    - humidity
    - visibility

- platform: plex
  host: !secret media_ip
  port: !secret plex_port
  name: Plex

- platform: time_date
  display_options:
  - 'date_time'

- platform: cpuspeed

