# Weather Underground
- platform: wunderground
  api_key: !secret weather_api_key
  monitored_conditions:
    - alerts
    - temp_f
    - weather

- platform: yweather
  monitored_conditions:
    - weather
    - temperature
    - humidity
    - visibility

- platform: plex
  host: !secret media_ip
  port: !secret plex_port
  name: Plex

- platform: time_date
  display_options:
  - 'date_time'

- platform: cpuspeed

- platform: waze_travel_time
  origin: Montgomery, AL
  destination: Troy, AL
  region: 'US'
  name: MGM to Troy

- platform: waze_travel_time
  origin: Birmingham, AL
  destination: Montgomery, AL
  region: 'US'
  name: BHM to MGM

- platform: waze_travel_time
  origin: Birmingham, AL
  destination: Tuscaloosa, AL
  region: 'US'
  name: BHM to Tuscaloosa

- platform: waze_travel_time
  origin: Montgomery, AL
  destination: Gulf Shores, AL
  region: 'US'
  name: MGM to Gulf Shores

