################################################################################
# Weather Underground
################################################################################
- platform: wunderground
  api_key: !secret weather_api_key
  monitored_conditions:
    - alerts
    - temp_f
    - weather

################################################################################
# Yahoo Weather
################################################################################
- platform: yweather
  monitored_conditions:
    - weather
    - temperature
    - humidity
    - visibility

################################################################################
# Plex Media Server activity
################################################################################
- platform: plex
  host: !secret media_ip
  port: !secret plex_port
  name: Plex

################################################################################
# Current Date and Time
################################################################################
# - platform: time_date
#   display_options:
#   - 'date_time'

################################################################################
# Travel Times # Travel Times # Travel Times # Travel Times #
################################################################################
- platform: waze_travel_time
  origin: Montgomery, AL
  destination: Troy, AL
  region: 'US'
  name: MGM to Troy

- platform: waze_travel_time
  origin: Troy, AL
  destination: Montgomery, AL
  region: 'US'
  name: Troy to MGM

- platform: waze_travel_time
  origin: Birmingham, AL
  destination: Montgomery, AL
  region: 'US'
  name: BHM to MGM

- platform: waze_travel_time
  origin: Troy, AL
  destination: Panama City Beach, FL
  region: 'US'
  name: Troy to PCB

- platform: waze_travel_time
  origin: Montgomery, AL
  destination: Atlanta, GA
  region: 'US'
  name: MGM to ATL

