################################################################################
# Close garage door when alarm set to home
################################################################################

- id: '1519348624408'
  alias: Secure Home, Stay
  trigger:
  - entity_id: alarm_control_panel.simplisafe
    from: disarmed
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.simplisafe
    from: armed_away
    platform: state
    to: armed_home
  condition: []
  action:
  - alias: ''
    data: {}
    service: cover.close_cover

################################################################################
# Send notification when garage door is open or closed
################################################################################

- id: garage_state_change
  alias: Garage State Change
  initial_state: 'on'
  trigger:
  - entity_id: cover.garage_door
    from: open
    to: closed
    platform: state
  - entity_id: cover.garage_door
    from: closed
    to: open
    platform: state
  condition: []
  action:
  - data:
      message: 'Garage door opened/closed'
    service: script.internal_notification

################################################################################
# Close garage door when alarm is set to away
################################################################################
 
- id: '1519775124178'
  alias: Secure Home, Away
  trigger:
  - entity_id: alarm_control_panel.home_security
    from: disarmed
    platform: state
    to: armed_away
  - entity_id: alarm_control_panel.home_security
    from: armed_home
    platform: state
    to: armed_away
  condition: []
  action:
  - data:
      entity_id: cover.garage_door_opener
    service: cover.close_cover

################################################################################
# Turn on window AC based on outdoor temperature
################################################################################
 
- id: '1520379769803'
  alias: Turn On Window AC
#  hide_entity: true
  trigger:
  - above: '82'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: off
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_on

################################################################################
# Turn off window AC at 11:45 PM or when temp is below 81F
################################################################################

- id: '1520379886802'
  alias: Turn Off Window AC
  trigger:
  - below: '81'
    entity_id: sensor.pws_temp_f
    platform: numeric_state
  - at: '23:45:00'
    platform: time
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: off
  action:
  - data:
      entity_id: switch.upstairs_ac
    service: switch.turn_off

################################################################################
# Garage Home while Secure Home
################################################################################

- id: '1521315030622'
  alias: Garage Home while Secure Home
  trigger:
  - entity_id: cover.garage_door
    from: closed
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_security
    state: armed_home
  action:
  - data:
      entity_id: switch.fireplace
    service: switch.turn_on
  - service: script.global_notification
    data:
      message: 'Garage door has opened while secured!'

################################################################################
# Power Down When Away
################################################################################

- id: power_down_when_away
  alias: Power Down When Away
  initial_state: True
  trigger:
  - entity_id: alarm_control_panel.simplisafe
    from: disarmed
    platform: state
    to: armed_away
  - entity_id: alarm_control_panel.simplisafe
    from: armed_home
    platform: state
    to: armed_away
  action:
  - data:
      entity_id: switch.master_tv
    service: switch.turn_off
  - data:
      entity_id: switch.living_tv_
    service: switch.turn_off
  - data:
      message: 'Power down has completed'
    service: script.global_notification

